name: Deploy Next.js to ECS

on:
  push:
    branches: [main, develop, feature/**]

jobs:
  deploy:
    name: Build and Deploy to AWS ECS
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    env:
      NEXT_PUBLIC_ENV: ${{ github.ref_name == 'main' && 'production' || 'develop' }}

    steps:
      - name: /****/ Checkout Code /****/
        uses: actions/checkout@v4

      - name: /****/ Setup Docker Buildx /****/
        uses: docker/setup-buildx-action@v3

      - name: /****/ Build & Push Docker Image to ECR /****/
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
            --build-arg NEXT_PUBLIC_ENV=${{ env.NEXT_PUBLIC_ENV }} \
            -t $IMAGE_TAG .
